# Speech Emotion Recognition Configuration

# Model Parameters
model:
  audio:
    sample_rate: 22050
    n_mfcc: 13
    hidden_size: 128
    num_layers: 2
    dropout: 0.3
    bidirectional: true
  
  visual:
    input_size: [224, 224]
    num_channels: 3
    backbone: "resnet18"
    pretrained: true
  
  fusion:
    hidden_size: 256
    num_classes: 5  # anger, fear, happiness, sadness, calm
    dropout: 0.3

# Training Parameters
training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  weight_decay: 0.0001
  patience: 10
  device: "auto"  # auto, cpu, cuda

# Data Parameters
data:
  datasets:
    - "RAVDESS"
    - "TESS"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  augmentation: true

# API Parameters
api:
  host: "0.0.0.0"
  port: 8000
  max_file_size: 50  # MB
  cors_origins: ["*"]

# Real-time Parameters
realtime:
  buffer_size: 1024
  inference_rate: 5  # Hz
  confidence_threshold: 0.7

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ser.log"
